administration:
    resource: "@AdministrationBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor