<?php

namespace AdministrationBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategories()
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c')
            ->where($qb->expr()->eq('c.deleted', 0))
            ->andWhere($qb->expr()->notIn('c.name', ':user'))
            ->setParameter('user', 'User')
            ->setMaxResults(10);

        return $qb->getQuery()->getResult();
    }

    public function findCategory($name)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c')
            ->where($qb->expr()->eq('c.name', ':name'))
            ->setParameter('name', $name);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
