<?php

namespace AdministrationBundle\Repository;

/**
 * UserProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProductRepository extends \Doctrine\ORM\EntityRepository
{
}
